zkonduit/ezkl

examples/conv2d_mnist/main.rs
examples/mlp_4d.rs
examples/smallonnx.rs
src/nn/affine.rs
src/nn/cnvrl.rs
src/nn/io.rs
src/tensor/mod.rs
src/tensor/val.rs
src/tensor/var.rs
src/tensor_ops/mod.rs

- removes input channels as generic on conv layers using:
-   4D kernels convolved with 3D inputs in `tensor_ops::convolution`
- allowing for N-d vectors on IOconfig (i.e N-d advice vectors, N-d inputs, N-d kernels)
- removing `[1,len]` shape requirement for 1-D input
**NOTE:** Swaps width and Height dims to be closer to `pytorch` norm
Resolves #18

refactor: fully dynamic conv layers

---

benches/affine.rs
benches/cnvrl.rs
benches/relu.rs
examples/conv2d_mnist/main.rs
examples/mlp_4d.rs
examples/smallonnx.rs
src/lib.rs
src/nn/affine.rs
src/nn/cnvrl.rs
src/nn/eltwise.rs
src/nn/mod.rs
src/tensor/mod.rs
src/tensor/ops.rs
src/tensor/val.rs
src/tensor_ops/mod.rs

- Moves `eltwise` to the `nn` module
- Implements `LayerConfig` on `EltwiseConfig`
- Simplifies  `LayerConfig`
- Fixes issue whereby `ValTensor` inner wouldn't reshape
- Removes all constant traits on `ConvConfig` (fully dynamic)

refactor: eltwise as layer

---

.gitignore
README.md
src/bin/ezkl.rs
src/commands.rs
src/lib.rs
src/onnx/mod.rs
src/onnx/onnxmodel.rs
src/tensor/val.rs
tests/integration_tests.rs

Adds SubCommands:
-  table      Loads model and prints model table
-  mock       Loads model and input and runs mock prover (for testing)
-  fullprove  Loads model and input and runs full prover (for testing)
-  prove      Loads model and data, prepares vk and pk, and creates proof, saving proof in --output
-  verify     Verifies a saved proof, returning accept or reject
-  help       Print this message or the help of the given subcommand(s)

feat: cli subcommands

---

src/tensor/mod.rs
src/tensor/ops.rs

- Adds a `tmax` function to the `TensorType` trait, which returns the larger of the two inputs
- the `max_pool2d` op computes the maximum for each slice by calling `fold` over the slice with `tmax`
Concerns:
- I'm not entirely sure about what operations are/aren't allowed for `AssignedCell`, `Assigned`, `Value` types.
- For the `f32` behavior, I had the `tmax` return the non-NAN value one of the operands of `tmax` was `f32::NAN`.
- for `pasta::Fp` values, should we handle negative numbers explicitly in the `tmax` function?

feat: add 2D max pooling to tensor ops

---

README.md
src/commands.rs

- Run examples in the README without having to manipulate logrows and bits params

fix: change defaults

---

src/bin/ezkl.rs

- Gives user suggestions on how to fix common OOR Lookup or Permutation errors. 
- `debug` logs give additional information to those errors
eg.

chore: helpful error messages for mock proving

---

benches/affine.rs
benches/cnvrl.rs
benches/range.rs
benches/relu.rs
examples/conv2d_mnist/main.rs
examples/mlp_4d.rs
src/circuit/eltwise.rs
src/circuit/fused.rs
src/circuit/range.rs
src/circuit/utils.rs
src/onnx/mod.rs
src/onnx/model.rs
src/onnx/node.rs
src/tensor/mod.rs
src/tensor/var.rs

- `VarTensor` now has a Vector of columns as inner type. The number of columns in the vector is determined by `K`(logrows). 
- We can query and assign over these vectors using a 1D index. 
- Also holds information as to the dimensionality of the underlying object it represents (`dims`). 
- Note that the `capacity` attribute of  `VarTensor`  is not equal to the product of `dims`. Instead it expresses the maximum potential capacity (number of entries) that this `VarTensor`  has been programmed to hold given `K`.

feat: controllable circuit shape

---

src/circuit/eltwise.rs
src/graph/model.rs
src/graph/node.rs

- During configuration we track already instantiated tables using a `BTree`. 
- Nodes that configure the same table op (eg. non-linearity with same re-scaling factor) share a reference to the same table config

refactor: reuseable tables

---

src/graph/mod.rs
src/graph/model.rs
src/graph/node.rs

- fixes the systematic underestimation of the number of required advices for fused layers. 
- fixes cases where we overestimate as well, we remove intermediary calcs / nodes from the advice requirements

fix:  number of advices calculation

---

README.md
benches/range.rs
benches/relu.rs
examples/mlp_4d.rs
src/circuit/eltwise.rs
src/circuit/range.rs
src/circuit/utils.rs
src/commands.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/vars.rs
src/pfsys/mod.rs
src/tensor/mod.rs
src/tensor/val.rs
src/tensor/var.rs
tests/integration_tests.rs

feat: flexible public / private variables

---

src/circuit/eltwise.rs
src/circuit/fused.rs
src/graph/node.rs

Updating `graph/node.rs` has been very error prone, with most of the errors stemming from the fact that we generate a default node outside the `opkind` match pattern and then update fields on that default node.
We also are lacking unit tests for some of the `circuit` layers, which is bad practice. 
Here we:

chore: more complete unit tests and node.rs cleanup

---

benches/cnvrl.rs

The introduction of a min number of used rows mean the `K` used in `benches/cnvrl.rs` is now insufficient. The benches currently fail with `NotEnoughRowsAvailable { current_k: 8 }`. Here we increase K to 9 to accomodate the new min number of used rows. 
We should make this min number tunable as highlighted in  #78

fix: conv benches K constant

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/commands.rs
src/execute.rs
src/pfsys/aggregation.rs
src/pfsys/mod.rs
tests/integration_tests.rs

Updates dependencies: 
```bash
plonk-verifier -> snark-verifier
halo2_wrong_ecc -> v2023_01_20
halo2_proofs -> v2023_01_20
halo2curves -> 0.3.1
```
Some of the updates made break the usage of pasta curves (see https://github.com/privacy-scaling-explorations/halo2curves/issues/23) and IPA commitments, which we remove the implementation for for now. 
**Note:** the plonk-verifier updates required a fork + a few fixes and updates that can be tracked [here](https://github.com/zkonduit/plonk-verifier). Will be hoping to merge them into the main PSE repo ASAP so we don't need to maintain a fork.

chore: update dependencies

---

Cargo.lock
Cargo.toml

https://github.com/privacy-scaling-explorations/snark-verifier/pull/24 merges some of the changes we made to the snark-verifier repo. 
Can now update Cargo.toml to point to the updated upstream, rather than our fork.

chore: bump snark-verifier to upstream

---

README.md
src/commands.rs
src/execute.rs
src/pfsys/evm/aggregation.rs
src/pfsys/evm/mod.rs
src/pfsys/mod.rs
tests/integration_tests.rs

In anticipation of #105 and #104, `pfsys` has a new EVM submodule which holds the methods for aggregate proof generation. 
- Introduces `./src/pfysys/evm` as a submodule
- Cleans up some of the cli command code

refactor: pfsys evm submodule

---

src/graph/model.rs

- We still had some references to fuseable ops (which are just regular polynomial constraints and named accordingly now in `circuit/polynomial.rs`

chore: update doc name references

---

.gitignore
Cargo.lock
Cargo.toml
README.md
fix_verifier_sol.py
src/commands.rs
src/execute.rs
src/pfsys/evm/single.rs
src/pfsys/mod.rs

This PR adds the ability to generate a Solidity verifier.
Here is a document that describes the steps that a user can take to generate such a verifier. It can serve as a quick start guide. https://hackmd.io/QOHOPeryRsOraO7FUnG-tg
Teams who want to build on ezkl and want to verify their proofs on-chain can now do so easily. This functionality is intended to be short-lived and only meant to make it easier teams at ETHDenver to use ezkl.
I have added a `--sol-code-path` parameter to the `create-evm-verifier` subcommand. This subcommand will write the Yul code generated to snark-verifier to this file, then run `fix_verifier_sol.py` on it, and save the output to the same file.
1. It rewrites the Yul code to be a Solidity contract with a `verify()` function that accepts a `uint256` array of …

feat: solidity verifier generation

---

Cargo.toml
examples/default_run_args.json
src/bin/ezkl.rs
src/commands.rs
src/execute.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/vars.rs
src/lib.rs
src/pfsys/evm/aggregation.rs
src/pfsys/evm/mod.rs
src/pfsys/mod.rs

To start creating easy to re-use config files across all run, we're moving the main run args (like the scale used, which variables are instances etc...) into a separate serializable struct -- which would make saving and loading said parameters much easier. 
We want this because these parameters (rather than the path parameters of each of the subcommands) are most critical for reproducibility.

refactor: run args as separate struct

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Verifier.json
fix_verifier_sol.py
src/bin/ezkl.rs
src/commands.rs
src/eth.rs
src/execute.rs
src/lib.rs
src/pfsys/evm/mod.rs
tests/integration_tests.rs

This PR does two main things:
1. Change the ABI of the `verify()` function in Solidity to:
```solidity
function verify(
uint256[] memory pubInputs,
bytes memory proof
) public view returns (bool)
```
Previously, the size of `pubInputs` had to be specified. This change makes it easier for the CI tests to run as the number of inputs is not known at compile-time.
2. Enable Solidity verification in the CI
The CI flow now includes verification of the generated Solidity verifiers for the models which can be verified in Solidity (the others create contracts that are too large to work).

chore: minor adjustment to the Solidity verify() function signature and integration of Solidity verification with the CI

---

.github/workflows/rust.yml
src/commands.rs

Prove and verify had different default values for transcripts. This PR

fix: prove + verify transcript defaults should match

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
README.md
src/eth.rs
src/execute.rs
src/pfsys/mod.rs

Our current serialization and deserialization pipeline for KZGParams (SRS) assumes a raw bytes serialization. Whereas the pre-converted SRS strings [here](https://github.com/han0110/halo2-kzg-srs), assume a `SerdeFormat::Processed` serialization. Here we: 
Resolves #116

feat: serialization compatibility for pre-generated SRS

---

.github/workflows/rust.yml
.gitignore
README.md
src/commands.rs
src/execute.rs
src/graph/model.rs
tests/integration_tests.rs

Determining the correct public outputs for a model is currently a bit of pain due to quantization here we introduce a new `forward` command which produces said quantized output as a `Vec<Vec<f32>>` and saves it to a new `.json` file: 
```bash 
Usage: ezkl forward --data <DATA> --model <MODEL> --output <OUTPUT>
Options:
-D, --data <DATA>      The path to the .json data file
-M, --model <MODEL>    The path to the .onnx model file
-O, --output <OUTPUT>  Path to the new .json file
-h, --help             Print help
```
Resolves #119

feat: vanilla model forward pass for output json generation

---

src/circuit/lookup.rs

As per #126 some of the steps whereby we convert a tensor of `AssignedCell` to a vector of `i32` are pretty opaque. This PR splits those steps out, adds more informative variable naming, and hopefully adds comments which provide context. 
Resolves #126

refactor: comment and split up integer value extraction for lookup

---

README.md

Previous instructions with regards to building `ezkl` had been unclear leading to bugs. 
This PR adds more details required to run `ezkl` properly by making the installation of `solc` more explicit.

add: build instructions

---

.github/workflows/rust.yml
README.md

Triggering new CI pipelines solely for readme updates is overkill.

chore: ignore readme updates when triggering actions

---

README.md

We have no documentation currently as to how to save and re-use arguments / configs across commands for portability / ease of use. 
Here we add such documentation.

chore: document config environment variable usage

---

.github/workflows/rust.yml
README.md
src/commands.rs
src/eth.rs
src/execute.rs
src/graph/model.rs

Deploying contracts is tough ! let us help you. 
```rust
/// Deploys an EVM verifier
#[command(name = "deploy-verifier-evm", arg_required_else_help = true)]
DeployVerifierEVM {
/// The path to the wallet mnemonic
#[arg(short = 'S', long)]
secret: PathBuf,
/// RPC Url
#[arg(short = 'U', long)]
rpc_url: String,
/// The path to the desired EVM bytecode file (optional), either set this or sol_code_path
#[arg(long)]
deployment_code_path: Option<PathBuf>,
/// The path to output the Solidity code (optional) supercedes deployment_code_path in priority
#[arg(long)]
sol_code_path: Option<PathBuf>,
// todo, optionally allow supplying proving key
},
```
Sending proofs to already deployed contracts is also tough ! Let us help with dat too: 
```rust
/// Send a proof to be verified to an already …
```

feat: commands to interact with the EVM

---

src/commands.rs
src/eth.rs
src/execute.rs

Some contracts we don't have the ABI for.  Adds a flag for triggering a raw call to the contract.

fix: allow for sending proofs to contracts with no-abi

---

src/graph/node.rs
src/tensor/mod.rs
src/tensor/ops.rs

`tensor::ops` has started to become overloaded and unintuitive. Here we implement standard ops such as `Add, Sub, Div, Mul` for `Tensor` to reduce notational burden and make usage of Tensors much simpler. 
For instance 
```rust
add(&vec![a, b])
```
Can be expressed as: 
```rust
a + b 
```

feat: impl standard tensor ops

---

Cargo.lock
Cargo.toml
benches/affine.rs
benches/cnvrl.rs
benches/range.rs
benches/relu.rs
src/bin/ezkl.rs
src/eth.rs

`env_logger` by default targets `stderr` not `stdout` which causes annoyances like those highlighted in #148; hindering the ability for external packages / languages to leverage the cli as a subprocess. Here we remedy this issue by removing `colog`, and explicitly setting the logging target to `STDOUT`. 
Whilst we're at it this PR also introduces a number of cosmetic improvements that were desperately needed. 
- logging timestamps
- logging metadata (the submodule it was called from). 
- pretty printing of JSON of cli command.
Resolves #148

fix: logs should go to `stdout` not `stderr`

---

.github/workflows/rust.yml
Cargo.toml
benches/accum_dot.rs
benches/dot.rs
src/circuit/accumulated_dot.rs
src/circuit/mod.rs
src/circuit/polynomial.rs
src/execute.rs
src/tensor/ops.rs
src/tensor/var.rs

A foundational component of many the operations constrained using polynomial args is the _dot product_. To make inroads into addressing and informing the claims of #161 this PR: 
- Introduces an accumulated polynomial argument composed of the base gate (with constraints $a_i*bi + m{i-1} = m_i$
```bash
| a0  | a1  | m     | s_dot | 
|-----|-----|-------|-------|
| a_i | b_i |m_{i-1}| s_dot |
|     |     |m_i    |       |
```
- Introduces an accumulated dot product operations, which returns the "transcript" (i.e intermediate ops) of the dot product: 
```rust
use ezkl_lib::tensor::Tensor;
use ezkl_lib::tensor::ops::accumulated::dot;
let x = Tensor::<i128>::new(
Some(&[5, 2]),
&[2],
).unwrap();
let y = Tensor::<i128>::new(
Some(&[5, 5]),
&[2],
).unwrap();
let expected = Tensor::<i128>::new( …
```

feat: accumulated dot product

---

Cargo.toml
benches/accum_dot.rs
benches/accum_matmul.rs
benches/matmul.rs
src/circuit/accumulated/dot.rs
src/circuit/accumulated/matmul.rs
src/circuit/accumulated/mod.rs
src/circuit/mod.rs
src/tensor/mod.rs
src/tensor/ops.rs
src/tensor/val.rs
src/tensor/var.rs

A foundational component of many the operations constrained using polynomial args is the _matrix to vector multiplication_. To make inroads into addressing and informing the claims of #161 this PR build on the accumulated dot product introduced in #162 . 
- Introduces an "init" polynomial argument composed of the base gate (with constraints $a_i*bi = m_i$
```bash
| a0  | a1  | m     | s_dot | 
|-----|-----|-------|-------|
| a_i | b_i | _     | s_dot |
|     |     | m_i   |       |
```
- This gate is used whenever the column enters a "new" matrix row to vector column dot product within an advice column. 
- Introduces an accumulated matrix multiplication, which returns the "transcript" (i.e intermediate ops) of the matmul: 
```rust
use ezkl_lib::tensor::Tensor;
use …
```

feat: accumulated mat-vec multiplications

---

.github/workflows/rust.yml
Cargo.toml
benches/add.rs
benches/pairwise_add.rs
src/circuit/accumulated/layouts.rs
src/circuit/accumulated/mod.rs

To make inroads into addressing and informing the claims of #161 this PR: 
- Introduces pairwise polynomial arguments composed of the base gates (with constraints $a_i + bi = m_i$, $a_i * bi = m_i$, $a_i -bi = m_i$
```bash
| a0  | a1  | m     | s | 
|-----|-----|-------|-------|
| a_i | b_i |m_{i}| s |
```
- Adds unit tests
- Adds benchmarks

feat: pairwise add, sub, mul

---

src/circuit/accumulated/mod.rs

Creates a non-constrained pad operation to add feature completeness to the accumulated ops being designed for #161.

feat: non-constrained pad

---

Cargo.lock
Cargo.toml
benches/relu.rs
src/commands.rs
src/eth.rs
src/execute.rs

Currently transactions (submitting proof, deploying verifier) require a local file containing a mnemonic. Though this is cool for testing it is generally bad OpSec. Here we enable the cli to connect directly to a plugged in ledger to sign transactions :)

feat: signing using ledger

---

src/lib.rs

As helpfully detailed in #199 nightly 1.71 release of rust/cargo treats `#[clap(flatten)]` as an unnecessary qualification  -- even though removing such a qualification means the cli doesn't compile (wonder if this is a broader bug ?). This PR relaxes some of our warning denials for `unnecessary_qualifications` to enable support for `1.71-nightly`. 
Thanks to @0xhank for catching this :) 
Resolves #199

fix: patch 1.71 clap qualifications

---

src/circuit/ops/layouts.rs
src/circuit/ops/mod.rs
src/circuit/ops/poly.rs
src/graph/node.rs
src/graph/utilities.rs
tests/integration_tests.rs

Creates the iff op which takes in three inputs `mask,a,b`: 
```rust
if mask > 0 { a } else { b }
```
It constrains mask to be boolean using the `IsBool` selector. 
As PreLu is gets decomposed into a Iff + other ops we use a prelu integration test to test the op.

feat: iff op

---

Cargo.lock
Cargo.toml
examples/conv2d_mnist/main.rs
examples/mlp_4d.rs
src/circuit/mod.rs
src/circuit/ops/hybrid.rs
src/circuit/ops/layouts.rs
src/circuit/ops/lookup.rs
src/circuit/ops/mod.rs
src/circuit/ops/poly.rs
src/circuit/table.rs
src/circuit/tests.rs
src/fieldutils.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/node.rs
src/graph/utilities.rs
src/graph/vars.rs
src/pfsys/evm/aggregation.rs
src/pfsys/mod.rs
src/tensor/mod.rs
src/tensor/val.rs
src/tensor/var.rs

New updates in hhttps://github.com/privacy-scaling-explorations/halo2wrong/pull/69 & https://github.com/privacy-scaling-explorations/poseidon/pull/9 mean we can upgrade halo2proofs to `v2023_04_20`. Which carries a number of useability benefits (listed [here](https://github.com/privacy-scaling-explorations/halo2/releases/tag/v2023_04_20)): 
Notably: 
- Extend Circuit trait to take parameters in config in https://github.com/privacy-scaling-explorations/halo2/pull/168 means we may be able to persist params without the repeated calls to `from_arg()` and will help with python bindings.

chore: upgrade  `halo2curves`, `halo2proofs`, `halo2wrong` 

---

src/execute.rs
src/python.rs
tests/python/binding_tests.py

Changes:
1. Refactor prove for #216 to `accept circuit_params_path`
2. Create python bindings and test for verify

feat: python bindings for verify

---

.cargo/config
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
examples/notebook/ezkl_demo.ipynb
examples/onnx/doodles/gen.py
examples/onnx/doodles/network.onnx
src/circuit/mod.rs
src/graph/utilities.rs
src/wasm.rs
tests/integration_tests.rs
tests/wasi_integration_tests.rs
tests/wasm.rs

- Building on #225 and #219, here we re-export `init_thread_pool` to enable for thread pools in web workers :) 
- CI tests also explicitly test in the browser rather than node

feat: re-export `init_thread_pool` in wasm modules

---

src/commands.rs
src/execute.rs
src/graph/model.rs

Optional deployment code path has caused confusion when creating the EVM verifier. Here we force its passage as an argument

refactor: require deployment code path

---

.github/workflows/benchmarks.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/graph/mod.rs
src/graph/model.rs
src/graph/node.rs
src/graph/utilities.rs
src/tensor/ops.rs

Removes dependencies that are barely used. Partially addresses #242

chore: cleanup cargo.toml

---

.github/workflows/pypi.yml

Changes:
1. Removes explicit architecture specification from apt installs as architecture libraries cannot be found. To rely on the installation environment instead.

fix: remove explicit architecture specification

---

Cargo.lock
Cargo.toml

Given the recent merger of thread safe regions in https://github.com/privacy-scaling-explorations/halo2/pull/180. Here we swap back to tracking the PSE fork in cargo. 
TODOs:
- merge changes in halo2wrong into PSE repo
- update PSE snark-verifier
Resolves #280 decisively

chore: update halo2proofs back to pse fork

---

.github/workflows/pypi.yml
requirements.txt

Changes:
1. There's a problem with the cross compilation linux toolchain for likely due to some python and gcc dependencies not being properly linked in the maturin-actions container used to compile. This PR will temporarily omit out `linux-cross` to enable builds on other platforms for the time being.

fix: comment out linux-cross

---

src/wasm.rs
tests/wasm.rs

This PR creates WASM bindings for:
Generating circuit parameters
Generating proving and verifying keys
Future work:
When WASM-bindgen multivalue is available, consolidate all three functions to one `setup()` function.

feat: wasm setup params

---

src/circuit/modules/poseidon.rs
src/commands.rs
src/eth.rs
src/execute.rs
src/graph/mod.rs
src/graph/model.rs
src/python.rs
src/tensor/ops.rs
src/wasm.rs
tests/integration_tests.rs
tests/python/1l_relu_circuit.settings
tests/python/1l_relu_settings.json
tests/python/binding_tests.py
tests/python/settings.json
tests/python/srs_utils.py
tests/wasm.rs

- Adds defaults for exported filenames
- renames kzg params to srs 
- renames circuit params to settings 
- splits gen_circuit_params into gen_settings and calibrate_settings to avoid conditional flag logic

refactor: avoid overloading "params"

---

src/graph/mod.rs

Anything above K=26 does not currently have easy to access public SRS (https://github.com/han0110/halo2-kzg-srs) and generating such SRS takes _an eternity_ effectively making suggested K values above 26 unusable. Here we cap calibrated K to 26.

fix: cap calibration logrows at max public srs

---

src/bin/ezkl.rs
src/execute.rs
src/lib.rs
src/logger.rs

- rayon is not a good fit for async because it operates on ordinary non-async functions, and blocks in operations like `for_each()`.
-  But since we're using async, we could avoid Rayon altogether and just spawn a task for each operation:
```rust
let tasks: Vec<_> = batches
.iter()
.map(|(k, v)| {
tokio::spawn(async move {
..do some calibration work 
})
})
.collect();
future::join_all(tasks).await;
```

fix: use `tokio` (not `rayon`) for calibration parallelism

---

.github/workflows/pypi.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml

Changes:
1. Uses vendored ssl instead of system ssl
2. Updates rust nightly version in ci to 2023-06-27
3. Updates ubuntu version in ci to ubuntu-latest or 22.04

fix: use vendored ssl

---

src/eth.rs
src/execute.rs

Rather than read the number of pub instances for a given verifier from assembly, we read it directly from the circuit instead in the create_evm_verifier execution function and its variants.

fix: move number of instances calculation as a param to pass to fix_verifier_sol. 

---

src/wasm.rs
tests/wasm.rs

Serializing human readable json files is a lot easier to do in a JS client side environment as opposed to bincode.

fix: replace `bincode` with `serde_json` in wasm bindings

---

src/eth.rs

Add gas estimation to verify function to see how much gas units, on-chain verification uses

chore: add gas estimate to verify function

---

contracts/AttestData.sol
contracts/QuantizeData.sol
contracts/VerifierBase.sol

*In order to prevent the verifier from accepting two version of the same pubInput, n and the quantity (n + P),  where n + P <= 2^256, we require that all pubInputs are stricly less than P.
*The reason for this is that the assmebly code of the verifier performs all arithmetic operations modulo P and as a consequence can't distinguish between n and n + P values.
Thank you so much to @arielgabizon for flagging this issue to us
:)

fix: limit the pubinput size to verifiers to be `<` P 

---

Cargo.lock
Cargo.toml
src/commands.rs

Want to take advantage of speedups detailed in https://github.com/privacy-scaling-explorations/halo2curves/pull/49

chore: update `halo2curves`

---

Cargo.toml
benches/accum_conv.rs
benches/accum_dot.rs
benches/accum_einsum_matmul.rs
benches/accum_matmul_relu.rs
benches/accum_sum.rs
benches/accum_sumpool.rs
benches/elgamal.rs
benches/pairwise_add.rs
benches/pairwise_pow.rs
benches/poseidon.rs
benches/relu.rs
examples/conv2d_mnist/main.rs
examples/mlp_4d_einsum.rs
src/bin/ezkl.rs
src/circuit/modules/elgamal.rs
src/circuit/modules/poseidon.rs
src/circuit/ops/layouts.rs
src/commands.rs
src/execute.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/vars.rs
src/lib.rs
src/pfsys/mod.rs
src/python.rs
src/tensor/mod.rs
src/tensor/val.rs
src/wasm.rs
tests/integration_tests.rs

Improves layout speed by a factor of 20 for dummy layouts and by a factor of 10 for "real" layouts. 
Prior setup phase: 
```bash 
[T] [1s, ezkl::circuit::ops::layouts] - filtering const zero indices took: 1.154125ms
[T] [1s, ezkl::circuit::ops::layouts] - assigning inputs took: 53.292µs
[T] [1s, ezkl::circuit::ops::layouts] - calculating accumulated dot took: 2.208µs
[T] [1s, ezkl::circuit::ops::layouts] - assigning output took: 23.167µs
[T] [1s, ezkl::circuit::ops::layouts] - dot layout took: 1.280833ms
```
New setup phase:  
```bash
[T] [1s, ezkl::circuit::ops::layouts] - filtering const zero indices took: 18.708µs
[T] [1s, ezkl::circuit::ops::layouts] - assigning inputs took: 66.917µs
[T] [1s, ezkl::circuit::ops::layouts] - calculating accumulated dot took: 3.833µs
[T] [1s, …
```

refactor: faster filtering algorithm for null consts

---

.github/workflows/rust.yml
README.md
examples/notebooks/ezkl_demo.ipynb
tests/py_integration_tests.rs

Changes:
1. Uses the ABCDE EZKL demo which goes through an end to end flow of training a model and deploying the model using remix
2. Updates the readme to use one-liner installation for both CLI and the Python bindings

docs: update default demo example and update readme

---

examples/onnx/boolean/gen.py
examples/onnx/boolean/input.json
examples/onnx/boolean/network.onnx
src/circuit/ops/hybrid.rs
src/circuit/ops/layouts.rs
src/circuit/ops/lookup.rs
src/circuit/ops/poly.rs
src/graph/input.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/utilities.rs
src/tensor/mod.rs
src/tensor/ops.rs
src/tensor/val.rs
src/tensor/var.rs
tests/integration_tests.rs

Unlocks `AND, OR, XOR, EQUALS, NOT` over inputs

chore: allow for boolean inputs

---

.github/workflows/wasm.yml

in nodejs/commonjs import from: `"main": "nodejs/ezkl.js"`
in browser/ejs import from `"module": "web/ezkl.js"`

fix: import wasm engine from mjs and cjs targets

---

examples/notebooks/data_attest.ipynb
examples/notebooks/encrypted_vis.ipynb
examples/notebooks/hashed_vis.ipynb
examples/notebooks/lstm.ipynb
examples/notebooks/voice_judge.ipynb
src/commands.rs
src/execute.rs
src/graph/input.rs
src/graph/mod.rs
src/graph/model.rs
src/graph/vars.rs
src/lib.rs
src/python.rs
src/wasm.rs
tests/integration_tests.rs
tests/wasm/settings.json

Currently we only matched the `batch_size` symbol -- which means the cli fails when multiple symbols are present. 
Here we replace the `batch_size` argument in `RunArgs` with a generic `variables` argument: 
```rust
pub struct RunArgs {
/// The tolerance for error on model outputs
#[arg(short = 'T', long, default_value = "0")]
pub tolerance: Tolerance,
/// The denominator in the fixed point representation used when quantizing
#[arg(short = 'S', long, default_value = "7")]
pub scale: u32,
/// The number of bits used in lookup tables
#[arg(short = 'B', long, default_value = "16")]
pub bits: usize,
/// The log_2 number of rows
#[arg(short = 'K', long, default_value = "17")]
pub logrows: u32,
/// Hand-written parser for graph variables, eg. batch_size=1
#[arg(short = 'V', long, value_parser = …
```

feat: generic symbol <> dimension size matching

---

src/circuit/ops/chip.rs
src/python.rs
tests/python/binding_tests.py

Currently expects a `dict`, should get behaviour to match rust cli, where struct / dict get auto-initialized from the provided f32 val.

fix: allow float values for `PyRunArgs` tolerance field

---

src/circuit/modules/elgamal.rs
src/graph/mod.rs
src/graph/modules.rs
src/wasm.rs
tests/wasm.rs

To prove locally in the browser we need a way to generate a witness file, as the prove method can only accept the quantized format of the raw model inputs stored in a witness file. The setup step (pk and vk generation) will be handled in python.

feat: gen witness wasm binding

---

src/eth.rs

In order to test verifiers that are above the spurious dragon 24.5 kb size limit, I have increased the contract code size limit to 1gb and disabled the block gas limit. Hopefully we never need to test an evm verifier above 1gb.

refactor: increase contract code limit to 1gb and disable block gas on anvil

---

src/graph/mod.rs
src/pfsys/mod.rs
src/python.rs
tests/python/binding_tests.py

Implements python function for poseidon hashing. 
Example usage: 
```python
message = [1.0, 2.0, 3.0, 4.0]
message = [ezkl.float_to_vecu64(x, 7) for x in message]
res = ezkl.poseidon_hash(message)
assert ezkl.vecu64_to_felt(
res[0]) == "0x0da7e5e5c8877242fa699f586baf770d731defd54f952d4adeb85047a0e32f45"
```
Implements python function for elgamal encryption and decryption. 
Example usage: 
```python
message = [1.0, 2.0, 3.0, 4.0]
felt_message = [ezkl.float_to_vecu64(x, 7) for x in message]
rng = [0 for _ in range(32)]
variables = ezkl.elgamal_gen_random(rng)
encrypted_message = ezkl.elgamal_encrypt(
variables.pk, felt_message, variables.r)
decrypted_message = ezkl.elgamal_decrypt(encrypted_message, variables.sk)
assert decrypted_message == felt_message
recovered_message = …
```

chore: python implementations of module functions

---

.github/workflows/rust.yml
.github/workflows/wasm.yml
tests/wasm/testWasm.test.ts
tests/wasm/utils.ts

Added JS based serialize/deserialize helper methods to ezkljs engine package. These helper methods are meant to replicate the `serde_json::from_slice` and `serde_json::to_vec` methods used in the rust based wasm tests [here](https://github.com/zkonduit/ezkl/blob/main/tests/wasm.rs)
To convert a JS object or string representation of an engine input, (e.i. proof, witness, setting, message, e.t.c.) call the `serialized` method, then pass the results to the respective method. 
To convert an engine output to a JS object, pass it to the `deserialized` method

feat: serialize/deserialize ezkljs/engine helper methods

---

.github/workflows/rust.yml
contracts/AttestData.sol
contracts/QuantizeData.sol
contracts/TestReads.sol
examples/notebooks/data_attest_hashed.ipynb
src/eth.rs
src/execute.rs
src/graph/input.rs
src/graph/mod.rs
src/graph/modules.rs
src/graph/vars.rs
tests/integration_tests.rs
tests/py_integration_tests.rs

This allows for the creation of on-chain test data that corresponds to the instances of poseidon and elgamal modules. 
Notably those instances have their quantization scales set to 1.0 and their decimal points set to 0 (as they are field elements already). 
TODO: 
@ethan-crypto currently the mulDiv for quantization fails in the case of decimal point set to 0. I wonder if there's some 0 division slipping through. Could you take a look ? 
```rust
failed: (code: 3, message: execution reverted: Math: mulDiv overflow, data: Some(String("0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000154d6174683a206d756c446976206f766572666c6f770000000000000000000000")))
```
To reproduce run `cargo nextest run …

feat: allow for hashed and elgamal vis for DA test data

---

.github/workflows/benchmarks.yml
Cargo.toml
benches/accum_matmul_relu_overflow.rs

```javascript
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 17.0s.
accum_matmul/pk/8       time:   [1.4004 s 1.4526 s 1.5087 s]                               
thrpt:  [5.3024  elem/s 5.5075  elem/s 5.7126  elem/s]
Benchmarking accum_matmul/prove/8: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 122.0s.
accum_matmul/prove/8    time:   [11.936 s 11.987 s 12.044 s]                                  
thrpt:  [0.6642  elem/s 0.6674  elem/s 0.6703  elem/s]
Benchmarking accum_matmul/pk/10: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 5.6s.
accum_matmul/pk/10      time:   [533.47 ms 548.48 ms 564.56 ms] …
```

chore: lookup overflow benches

---

src/commands.rs
src/eth.rs

chore: fix typos in comments

---

src/execute.rs

Changes:
1. `generateArtifact` now returns the artifact object itself. Query has been changed to reflect this.

fix: update artifact query

---

src/wasm.rs
tests/wasm.rs

We should be able to print the `proof.proof` of a proof files content as a hex string instead of a uint 8 array on the client.

feat: expose print proof hex in wasm

---

src/graph/mod.rs
src/lib.rs

Resolves #617. 
calibrate would correctly identify min/max on lookups BUT due to security buffer (2x multiplier), this value would occasionally overflow `i128` on extremely large values (`--release` allows this) and cause very strange lookup ranges to be adopted (eg. `(0, -2)`). 
Here we
- add sanity checks and validation for `RunArgs`. 
- Ensure overflow hard fails a calibration run

fix: calibrate lookup range i128 overflow on `--release` compile

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
tests/integration_tests.rs

allows for the  "all kzgcommit" settings to be verifiable on-chain.

fix: allow for 0 instance evm verifier

---

tests/integration_tests.rs

#364 
This is a sample implementation for only kzg_evm_kzg_input_prove_and_verify_ for now. Let me know what you think.
Approach:
* Add a hardfork enum
* Add a hardfork parameter for start_anvil and each test function.
* Use macro to make sure test run on each hardfork. Currently, we run London, Paris and latest blockchain fork.

chore: add hardfork test for kzg_evm_kzg_input_prove_and_verify

---

.github/workflows/pypi.yml

Changes:
1. Uses virtualenv on musl. This is to comply with (PEP-668)[https://peps.python.org/pep-0668/], which will prevent users from installing into the system python environment so as to not break system packages.

fix: use venv on musl linux

---

src/graph/node.rs

There's a bunch of code duplication, I think we can simplify the implementation. As I wrote in the method doc, since each associated (inner) value of `SupportedOp` implements `Op`, an aux method to extract this inner value can be re-used across the board.
Unless, of course, you've envisioned to have the inner value change at some point / add sth that does not impl `Op`.

Simplify the code for `impl Op<Fp> for SupportedOp`

---

src/commands.rs

Changes:
1. Adds more hints for calibration, as the current clap messages may be incomplete and ambiguous.

docs: add more helpful hints for calibration

---

src/execute.rs
src/pfsys/mod.rs

```rust
/// An application snark with proof and instance variables ready for aggregation (raw field element)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Snark<F: PrimeField + SerdeObject, C: CurveAffine>
where
C::Scalar: Serialize + DeserializeOwned,
C::ScalarExt: Serialize + DeserializeOwned,
{
/// the protocol
pub protocol: Option<PlonkProtocol<C>>,
/// public instances of the snark
pub instances: Vec<Vec<F>>,
/// the proof
pub proof: Vec<u8>,
/// hex encoded proof
pub hex_proof: Option<String>,
/// transcript type
pub transcript_type: TranscriptType,
/// the split proof
pub split: Option<ProofSplitCommit>,
/// the proof instances as rescaled floats
pub pretty_public_inputs: Option<PrettyElements>,
/// timestamp
pub timestamp: Option<u128>,
}
```

chore: hex encoded (optional) proof field

---

src/execute.rs
src/pfsys/mod.rs
src/python.rs
src/wasm.rs

Changes:
1. prepend `0x` to the `hex_proof` for consistency and to match what the evm generally expects.

fix: prepend 0x to proof

---

Cargo.lock
Cargo.toml

fix for icicle being static and non-PIC, 
strange but only [`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`](https://github.com/ingonyama-zk/icicle/blob/45b00fb1966cb236979f03f9068f6db9bf59f41e/icicle/CMakeLists.txt#L57C17-L57C17) seems working while other options and flags should work as well

Fix for linking issue 

---

src/graph/model.rs

As discussed with other onnx users. ONNX standard for `Gather` can be rather inconsistent rules w.r.t to resulting dimensionality of output (sometimes adding new singleton dims .... sometimes not). Here we accomodate all standards by reshaping the output to ONNX's expected dimensionality.
Resolves #677

fix: accomodate different axes rules for `gather` op

---

examples/notebooks/ezkl_demo.ipynb

Changes:
1. The default settings for ezkl will generally set logrows at a value such that it may overload google colab free tier. To make the `ezkl_demo.ipynb` setup step executable within google colab free tier, we cap the `max_logrows` at `17` within `calibrate-settings`.

docs: set `max_logrows` for `calibrate_settings` in ezkl_demo

---

src/python.rs

Use version from Cargo.toml as the python module version. Resolves #692.

fix: add `__version__` to python bindings

---

README.md
src/circuit/table.rs
src/graph/mod.rs
src/tensor/var.rs

We currently re-extend logrows to accomodate constant and constraint overflow _after_ circuit creation. This can cause issues when extended K doesn't fit into the field size. 
Fixes #741

fix: logrows reset after graph creation can cause extended K overflow

---

src/graph/mod.rs

Addresses some of the giant logrows that stem from constants in #741

refactor: apply num-inner cols to constant assignments as well

---

.github/workflows/large-tests.yml
.github/workflows/npm.yml
.github/workflows/release.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
rust-toolchain
src/circuit/table.rs

When compressing (or not) selectors we make the calculation of the selector polys optional for verification so as to fit in low memory contexts (wasm etc...). 
Those polynomials are calculated  exclusively during key generation.

feat: make selector polynomials optional

---

install_ezkl_cli.sh

The install_ezkl_cli.sh script is supposed to add the `EZKL_DIR` to the `PATH` if it's not already present. However, due to a typo in the variable name (`EZKl_DIR` instead of `EZKL_DIR`), the script fails to correctly check if the directory is already in the PATH, and consequently, it always adds the directory to the `PATH` even if it's already there.
So this PR just fixes the typo.

Prevent multiple additions of `EZKL_DIR` to `PATH` in install_ezkl_cli.sh

---

src/lib.rs

Changes
1. The initial docstring prompts a user to input `kzgcommit` which doesn't exist now. If a user puts in `kzgcommit` the value will default to `private` instead. Adds `polycommit` into the docstring.

docs: add polycommit to RunArgs

---

src/commands.rs
src/eth.rs
src/execute.rs
src/python.rs
tests/integration_tests.rs
tests/python/binding_tests.py

Create an `encode-evm-calldata` helper function for folks that don't want to interact with contracts using ezkl tooling. 
Generally takes in: 
- proof path (we turn the proof into calldata) 
- calldata path (path to save the calldata) 
- vk_addr (optional vk addr if the vk is deployed as a separate contract) 
Usage in cli
```bash
ezkl encode-evm-calldata --proof-path <OPTIONAL_PATH_TO_PROOF> --calldata-path <OPTIONAL_PATH_TO_CALLDATA> --vk-addr <OPTIONAL_VK_ADDR>
```
In python the calldata is _also_ returned as an python object ... so you can use it directly in your python script 
```python
calldata = ezkl.encode_evm_calldata(proof_path, calldata_path)
assert os.path.isfile(calldata_path)
assert len(calldata) > 0
... do stuff with calldata
```

feat: create encode-evm-calldata in cli and python

---

.github/workflows/release.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/circuit/tests.rs
src/eth.rs

take advtange of the perf updates in https://github.com/zkonduit/halo2/pull/14

chore: perf updates

---

src/commands.rs
src/execute.rs

Clarify usage cues in ezkl CLI output

docs: improve cli friendliness

---

.github/workflows/update-ios-package.yml

- Fix the git tags not being pushed to the `ezkl-swift-package` (needed for Swift PM version management)
- Keep the `ezkl-swift-package` test assets in sync with the `ezkl` test assets by pushing the assets from the `ezkl /tests/assets` to `ezkl-swift-package/Tests/EzklAssets` on every ios package update trigger

fix: ios package update workflow tags & tests assets

---

.github/workflows/pypi.yml
docs/python/requirements-docs.txt

Changes:
1. Remove armv7, this is causing recent releases to fail. Also raspberry pi 4s are using aarch64 atm so it might not be very useful to support armv7 as it is dated and causing weird bugs.
2. Remove v0.0.0 from the requirements in sphinx docs to download the recent pypi release instead.

ci: remove armv7 and remove `v0.0.0` from auto python docs

---

src/lib.rs

- **"Bindings managment"** should be **"Bindings management"**.
"Managment" is a common misspelling of "management."
Fixed.

fix: typo in lib.rs

---

.github/workflows/pypi-gpu.yml
.github/workflows/pypi.yml

Changes:
1. Reduce non-determinism in builds by specifying major and minor versions in `/pypa/gh-action-pypi-publish`

fix: revert pypi to 1.11.0

---

Cargo.lock
Cargo.toml

Summary:
This PR updates the existing ICICLE MSM operations to use the latest version of ICICLE v2 and also enables NTT and INTT operations to be executed on the GPU via ICICLE.
Creds to @emirsoyturk for the work here on h2

feat: ICICLE MSM and NTT integration

---

Cargo.toml
benches/zero_finder.rs
src/eth.rs
src/graph/utilities.rs
src/tensor/val.rs

Currently constant filtering uses parallelism like a hammer _but_ for `einsum` operations where `dot` and `constant` filtering may be called repeatedly for MANY small arrays (eg. `einsum ijk,ijk->ij` where input dims are `[1024,1024,2]` we call it 1024*1024 times for arrays of size 2 which, induces terrible overhead from spinning up threads. 
Instead we should use sequential search methods for smaller arrays, lest we want to avoid this overhead. 
Here we also leverage benchmarks to get a rough threshold where we should switch from sequential to a parallel search for constants. On a M3 Max the results are below, giving us a rough crossover point of 1mil elements. 
```
zero_finding/sequential_1000
time:   [1.0408 µs 1.0438 µs 1.0495 µs]
Found 1 outliers among 10 measurements (10.00%)
1 …
```

fix: const filtering strat is size dependent

---

.github/workflows/pypi-gpu.yml
.github/workflows/pypi.yml
pyproject.toml

Changes:
1. Should fix the error found in this [action](https://github.com/zkonduit/ezkl/actions/runs/12518396492/job/34920777294)
```
💥 maturin failed
Caused by: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
```
2. Adds `version` into `pyproject.toml`
3. Adds sed substitution in the actions scripts to replace `0.0.0` with the respective version tag for the action

fix: add version string and sed

---

.github/workflows/benchmarks.yml
src/graph/mod.rs
src/graph/model.rs
src/tensor/var.rs

`ok_or` can eagerly execute printouts without actually returning an error value, making it seem like a process has failed (when it hasnt)

fix: eager exec of `ok_or` error prints

---

.github/workflows/swift-pm.yml

This PR resolves an issue in the CI pipeline where `zsh` would prompt the user for confirmation (`y`) during the file deletion step (`rm -rf *`), which was not handled by the script. This caused subsequent tests to fail due to missing files.
- Replaced `rm -rf *` with a safer approach that deletes the entire directory (`rm -rf`) and recreates it (`mkdir -p`).
- Ensured all required testing files are copied into the recreated directory.

fix: swift pm ci issue with updating testing files

---

.github/workflows/rust.yml

This PR fixes a CI issue in `rust.yml` where missing test files caused failures. 
- Added steps to update `ezkl-swift-package/Tests/EzklAssets/` with required test assets (`kzg.srs`, `input.json`, `model.compiled`, `settings.json`).

 fix: update test files in CI pipeline

---

.github/workflows/benchmarks.yml
.github/workflows/engine.yml
.github/workflows/large-tests.yml
.github/workflows/pypi-gpu.yml
.github/workflows/pypi.yml
.github/workflows/release.yml
.github/workflows/rust.yml
.github/workflows/static-analysis.yml
.github/workflows/swift-pm.yml
Cargo.lock
Cargo.toml
src/tensor/mod.rs
tests/integration_tests.rs

This pull request integrates the experimental metal GPU acceleration for MSM solving recently added to [`halo2`](https://github.com/zkonduit/halo2/pull/20) crate, by bumping its version, as well as removes support for the old `metal` feature from EZKL.

feat: metal acceleration for MSM solving

---

src/circuit/modules/polycommit.rs
src/circuit/modules/poseidon.rs

Hi! I fixes 404s links in the `polycommit.rs` and `poseidon.rs` modules.

fix: broken links in polycommit.rs and poseidon.rs

---

src/bindings/python.rs
src/circuit/ops/layouts.rs
tests/wasm.rs

Hi! I stumbled upon a few typos in the comments and documentation, and they were bugging me. Here's what I fixed:  
- In `python.rs`, **"represnted"** and **"addess"** are now **"represented"** and **"address."**  
- In `layouts.rs**, there were some weird words like **"ouput,"** **"occurence,"** and **"contraints"** — now they're all correct.  
- In `wasm.rs`, someone wrote **"comiled"** instead of **"compiled"** — fixed that too.  
No magic here, just small tweaks for clarity and order.

chore: fix typos in comments and docs

---

src/commands.rs
src/execute.rs

You can now pass data as a raw string to gen-witness using @<file_path> as an argument to data: 
```bash
ezkl gen-witness -D @input.json
```

chore: pass in raw data for gen-witness from file

---

src/bindings/python.rs

Fix logical error in ipa_commit function - use Commitments::IPA instead of Commitments::KZG when getting SRS path to ensure correct SRS file type is used for IPA commitments.

fix: correct commitment type in ipa_commit function
