Cargo.toml, src/affine1d.rs, src/cnvrl_generic.rs, src/cnvrl_generic/util.rs, src/conv2d_mnist_example.rs, src/eltwise.rs, src/lib.rs, src/mlp.rs
Remove constant generic expressions and add reusable tables in elementwise functions
=> No cnst gen exp

Cargo.toml, README.md, src/onnx/onnxmodel.rs
- Displays a table representation of extracted OnnxNodes
- Uses enum representation for LayerHyperParams
- Implements Display on select enums
=> feat: debug display of onnx model

tests/integration_tests.rs
Onnx integration tests that run the command-line tool.
=> feat: integration tests

README.md, src/bin/ezkl.rs, src/onnx/model.rs
- adds a tutorial for generating onnx files from python in Readme
=> chore: python tutorial

src/bin/ezkl.rs, src/circuit/eltwise.rs, src/circuit/fused.rs, src/circuit/utils.rs, src/lib.rs, src/tensor/mod.rs, src/tensor/var.rs
- removes most unwraps and instead adds more informative error messages
=> chore: more informative errors

src/circuit/fused.rs, src/fieldutils.rs, src/onnx/model.rs, src/onnx/node.rs, src/onnx/utilities.rs, src/pfsys/kzg/mod.rs, src/tensor/mod.rs, src/tensor/ops.rs
Implement batch norm and scale and shift. Changes to conv to cover the case where no bias is provided.
=> feat: conv improvements, batchnorm, scale and shift

.github/workflows/rust.yml, Cargo.toml, README.md, src/commands.rs, src/tensor/var.rs, tests/integration_tests.rs
=> chore: cleanup integration tests

benches/affine.rs, benches/cnvrl.rs, benches/range.rs, benches/relu.rs, examples/conv2d_mnist/main.rs, examples/mlp_4d.rs, src/circuit/eltwise.rs, src/circuit/fused.rs, src/circuit/range.rs, src/commands.rs, src/graph/vars.rs, src/tensor/var.rs
This PR makes the tensor max value configurable via a CLI arg
closes #78
=> feat: make max_rotations configurable

.github/workflows/rust.yml, Cargo.toml, src/circuit/eltwise.rs, src/circuit/fused.rs, src/graph/model.rs, src/graph/node.rs, src/graph/vars.rs, src/lib.rs, src/pfsys/aggregation.rs, src/tensor/ops.rs, src/tensor/val.rs
Recent changes to docs broke some of the docs compilation. We should add docs to the CI tests / Github Actions to prevent those sorts of failures in the future !
=> add: docs to ci tests

.github/workflows/rust.yml
- use github larger runners beta
=> chore: use larger runners

.github/workflows/rust.yml, src/graph/model.rs, src/graph/node.rs, src/pfsys/mod.rs, tests/integration_tests.rs
Need some integrations tests that test for negative examples i.e examples that should fail !
=> chore: negative example integration tests

src/circuit/mod.rs, src/graph/model.rs, src/tensor/var.rs
Tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust)
Opinions on this one loosely held, I’m happy to adapt.
=> refactor: exact instances of Option / Result combinators

README.md
=> chore: new readme banner

src/circuit/accumulated/layouts.rs, src/circuit/accumulated/mod.rs
Building on #169 which implement 0 rotation elementwise tensor addition, multiplication, and subtraction to address #161. Here we implement batch norm type operations (scale and shift) using these building blocks.
=> feat: batchnorm using 0 rotation add and mult

.github/workflows/rust.yml, Cargo.toml, benches/accum_sum.rs, benches/sum.rs, benches/sumpool.rs, src/circuit/accumulated/layouts.rs, src/circuit/accumulated/mod.rs, src/tensor/ops.rs
Accumulated sum argument. Goes towards #161
=> feat: accum sum

src/graph/utilities.rs, src/tensor/mod.rs
=> feat: error checks for significant bit truncation.

.gitignore, README.md, examples/notebook/ezkl_demo.ipynb
Creates a jupyter notebook demo for a large conv network in `examples/notebook`.
=> chore: jupyter notebook demo

.github/workflows/pypi.yml
Changes:
1. Remove missing library
=> fix: remove missing libraries

.github/workflows/pypi.yml
Changes:
1. add libc6-dev libraries for arm cross compilation
=> fix: add libc6-dev libraries for arm cross compilation

.github/workflows/pypi.yml
Changes:
1. Includes libusb in build action
=> fix: include libusb

.github/workflows/pypi.yml
Changes:
1. Add cross compile library for libatomic
=> fix: add cross compile library for libatomic

examples/conv2d_mnist/main.rs, src/execute.rs, src/pfsys/mod.rs
=> chore: add decimal place to timings

.github/workflows/release.yml, Cargo.lock, Cargo.toml, benches/accum_conv.rs, benches/accum_dot.rs, benches/accum_einsum_matmul.rs, benches/accum_matmul_relu.rs, benches/accum_pack.rs, benches/accum_sum.rs, benches/accum_sumpool.rs, benches/pairwise_add.rs, benches/pairwise_pow.rs, benches/relu.rs, src/commands.rs, src/execute.rs, src/pfsys/mod.rs, src/pfsys/srs.rs, src/python.rs, tests/python/binding_tests.py
=> feat: `get_srs` command 

.github/workflows/rust.yml
- Offers more granular test timings 
- Offers cleaner outputs and visibility 
- Its pretty !
=> chore: use nextest in ci

.github/workflows/release.yml, Cargo.lock, Cargo.toml, src/graph/mod.rs, src/graph/model.rs, tests/wasm/settings.json
=> chore: add current version to `settings.json`

Cargo.lock, Cargo.toml
=> chore: bump tract

src/commands.rs, src/eth.rs, src/execute.rs, src/python.rs
Added back solc optimizer runs as an optional param to the deploy evm command as requested by @HadiEsna
=> feat: add solc optimizer runs param to deploy evm command

.github/workflows/rust.yml, benches/elgamal.rs, benches/poseidon.rs, src/circuit/modules/elgamal.rs, src/circuit/modules/mod.rs, src/circuit/modules/planner.rs, src/circuit/modules/poseidon.rs, src/graph/modules.rs, tests/wasm.rs
=> fix: exact input - row num relationship for modules

src/circuit/ops/region.rs
Another 20-30% speed up on large models for layouts.
=> refactor: wrap region in `RefCell` for speed

src/eth.rs, src/execute.rs, src/graph/input.rs, src/graph/mod.rs, src/graph/model.rs, src/pfsys/evm/mod.rs, src/pfsys/mod.rs, src/pfsys/srs.rs
=> chore: more descriptive loading errors

src/execute.rs, src/graph/utilities.rs, src/tensor/mod.rs
No hard fail during calibration for truncation
Resolves #456
=> fix: no panic for sig bit truncation

.github/workflows/benchmarks.yml, .github/workflows/large-tests.yml, .github/workflows/pypi.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/tagging.yml, .github/workflows/wasm.yml
checkout@v3 is very flaky at this moment. Updating to v4.
https://github.com/actions/checkout/issues/1450
=> ci: actions checkout v4

Cargo.toml
Resolves https://github.com/zkonduit/ezkl/discussions/452
=> refactor: default copy constraint algo

examples/notebooks/set_membership.ipynb
Also added sanity check tests inside the notebook 👍
=> fix: manually hash set inputs for set_membership notebook

examples/notebooks/variance.ipynb, src/graph/utilities.rs
Reduces error for singleton div from 0.98% to 0.08%
=> refactor: replace small mult with `div` lookup

.github/workflows/rust.yml, Cargo.lock, src/circuit/ops/chip.rs, src/circuit/ops/lookup.rs, src/circuit/tests.rs, tests/integration_tests.rs
- Integration tests for `mock-aggr` now use lookup overflow to stress test this
=> fix: rm identity quotient chunks to allow for aggregation on ♾️ lookup

.github/workflows/wasm.yml
This reverts commit 8770720cb32fc2e410ac2906f91aea849f55e31c.
=> fix: revert #552

.github/workflows/wasm.yml
Needed to add a comma to the "web/utils.js" and "nodejs/utils.js"
=> fix: separate utils.js for web and nodejs bundles

README.md
=> docs: link to blog for technical writeups

.github/workflows/rust.yml, examples/notebooks/tictactoe_autoencoder.ipynb, examples/notebooks/tictactoe_binary_classification.ipynb, tests/py_integration_tests.rs
Changes:
1. Adds the tictactoe examples (binary classification, anomaly detection) as part of tests.
=> docs: add tictactoe examples

src/graph/mod.rs, src/graph/model.rs, tests/output_comparison.py
=> fix: increase lookup overflow slack for complex models

src/circuit/ops/layouts.rs, src/commands.rs, src/eth.rs, src/graph/mod.rs, src/tensor/ops.rs
Hey, I found a few typos. Three of them are error messages, the rest are comments. This is a minor typo that doesn't require any testing. Have a nice evening :).
=> chore(src): typo fix

.github/workflows/rust.yml, examples/notebooks/ezkl_demo.ipynb, examples/notebooks/nbeats_timeseries_forecasting.ipynb, examples/notebooks/variance.ipynb, src/execute.rs, src/graph/mod.rs, tests/integration_tests.rs, tests/py_integration_tests.rs
=> fix: calibrate from total min/max on lookups rather than individual x

examples/notebooks/data_attest.ipynb, examples/notebooks/kzg_vis.ipynb, examples/notebooks/simple_demo_public_network_output.ipynb, examples/notebooks/tictactoe_binary_classification.ipynb, examples/notebooks/world_rotation.ipynb
found few typos while reading the docs.
=> chore(examples): proofreading the notebooks

README.md, install_ezkl_cli.sh
Changes:
1. Moves the `install_ezkl_cli.sh` script into the ezkl repo
2. Updated README.md
=> fix: move `install_ezkl_cli.sh` into main repo

src/commands.rs, src/execute.rs, src/python.rs, tests/integration_tests.rs
=> fix: rm optional bool flags

Cargo.lock, Cargo.toml, install_ezkl_cli.sh, src/bin/ezkl.rs, src/commands.rs, src/execute.rs
Call `ezkl update` to get latest version
=> chore: ezkl self update

Cargo.lock, Cargo.toml
- Feature gated
- More memory backpressure
=> feat: parallel polynomial reads in halo2

.github/workflows/engine.yml, .github/workflows/large-tests.yml, .github/workflows/pypi.yml, .github/workflows/release.yml, .github/workflows/rust.yml, Cargo.lock, rust-toolchain
=> fix: bump compiler to latest to accomodate latest serde `diagnostic`

.github/workflows/pypi.yml
=> ci: typo in pypi script

.github/workflows/pypi.yml
Changes:
1. Upgrades `run-on-arch` which addresses the arm dependency issues
=> fix: upgrade run-on-arch

.github/workflows/static-analysis.yml
Changes:
1. Adds the `zizmor` static analysis tool as part of the CI. It seems like zizmor checks for gh actions only.
=> feat: add zizmor gh action

src/bindings/python.rs, src/execute.rs, src/graph/input.rs, src/graph/mod.rs, tests/integration_tests.rs
Also makes gen-witness and calibrate-settings sync
=> refactor: DataSource enum -> struct
